-- ============================================================
-- 시딩 후 정합성 검증 쿼리 세트 (자동 생성)
-- 생성: 2026-04-22T13:11:16
-- 
-- 실행 방식: 
--   psql -h <host> -U <user> -d bank_v2 -f verification_queries.sql > report.txt
--
-- 모든 쿼리는 violation 행 수를 반환 (0이면 정상)
-- hard severity 규칙은 반드시 0이어야 함
-- soft severity 규칙은 권장 허용치 내여야 함
-- ============================================================

SET search_path TO adw_v2;



-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 1. 기본 검증 (행 수 · 테이블 존재)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- 1.1 전체 테이블 행 수 vs cardinalities.json 기대치
SELECT 'TABLE_ROW_COUNT' AS check_name, 
       schemaname, relname AS table_name, n_live_tup AS actual_rows
FROM pg_stat_user_tables
WHERE schemaname = 'adw_v2'
ORDER BY n_live_tup DESC
LIMIT 30;

-- 1.2 비어있는 테이블 (볼륨 0 또는 시딩 실패)
SELECT 'EMPTY_TABLE' AS check_name, relname AS table_name
FROM pg_stat_user_tables
WHERE schemaname = 'adw_v2' AND n_live_tup = 0
ORDER BY relname;

-- 1.3 볼륨 편차 검증 (expected vs actual > 20%)
-- (수동 비교 필요 - cardinalities.json의 volume 참조)



-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 2. FK 참조 무결성 (fk_graph.json 엣지 기반)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- 2.1 핵심 마스터별 FK 참조 무결성 (orphan 찾기)

-- CSC002M.CSN → CSC001M.CSN
SELECT 'FK_ORPHAN_CSC002M_CSN' AS check_name, COUNT(*) AS violations
FROM CSC002M c
WHERE c.CSN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CSC001M p WHERE p.CSN = c.CSN);

-- CSC003M.CSN → CSC001M.CSN
SELECT 'FK_ORPHAN_CSC003M_CSN' AS check_name, COUNT(*) AS violations
FROM CSC003M c
WHERE c.CSN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CSC001M p WHERE p.CSN = c.CSN);

-- CSC004M.CSN → CSC001M.CSN
SELECT 'FK_ORPHAN_CSC004M_CSN' AS check_name, COUNT(*) AS violations
FROM CSC004M c
WHERE c.CSN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CSC001M p WHERE p.CSN = c.CSN);

-- CSC005M.CSN → CSC001M.CSN
SELECT 'FK_ORPHAN_CSC005M_CSN' AS check_name, COUNT(*) AS violations
FROM CSC005M c
WHERE c.CSN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CSC001M p WHERE p.CSN = c.CSN);

-- CSC005M.CEO_CSN → CSC001M.CSN
SELECT 'FK_ORPHAN_CSC005M_CEO_CSN' AS check_name, COUNT(*) AS violations
FROM CSC005M c
WHERE c.CEO_CSN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CSC001M p WHERE p.CSN = c.CEO_CSN);

-- CMI002H.BRCD → CMI001M.BRCD
SELECT 'FK_ORPHAN_CMI002H_BRCD' AS check_name, COUNT(*) AS violations
FROM CMI002H c
WHERE c.BRCD IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI001M p WHERE p.BRCD = c.BRCD);

-- CMI003M.BRCD → CMI001M.BRCD
SELECT 'FK_ORPHAN_CMI003M_BRCD' AS check_name, COUNT(*) AS violations
FROM CMI003M c
WHERE c.BRCD IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI001M p WHERE p.BRCD = c.BRCD);

-- CMI003M.UPPR_BRCD → CMI001M.BRCD
SELECT 'FK_ORPHAN_CMI003M_UPPR_BRCD' AS check_name, COUNT(*) AS violations
FROM CMI003M c
WHERE c.UPPR_BRCD IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI001M p WHERE p.BRCD = c.UPPR_BRCD);

-- CMI005M.BRCD → CMI001M.BRCD
SELECT 'FK_ORPHAN_CMI005M_BRCD' AS check_name, COUNT(*) AS violations
FROM CMI005M c
WHERE c.BRCD IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI001M p WHERE p.BRCD = c.BRCD);

-- CMI006H.PRE_BRCD → CMI001M.BRCD
SELECT 'FK_ORPHAN_CMI006H_PRE_BRCD' AS check_name, COUNT(*) AS violations
FROM CMI006H c
WHERE c.PRE_BRCD IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI001M p WHERE p.BRCD = c.PRE_BRCD);

-- PFP003M.PDN → PFP001M.PDN
SELECT 'FK_ORPHAN_PFP003M_PDN' AS check_name, COUNT(*) AS violations
FROM PFP003M c
WHERE c.PDN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM PFP001M p WHERE p.PDN = c.PDN);

-- PFP004M.PDN → PFP001M.PDN
SELECT 'FK_ORPHAN_PFP004M_PDN' AS check_name, COUNT(*) AS violations
FROM PFP004M c
WHERE c.PDN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM PFP001M p WHERE p.PDN = c.PDN);

-- PFP005M.PDN → PFP001M.PDN
SELECT 'FK_ORPHAN_PFP005M_PDN' AS check_name, COUNT(*) AS violations
FROM PFP005M c
WHERE c.PDN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM PFP001M p WHERE p.PDN = c.PDN);

-- PFP006M.PDN → PFP001M.PDN
SELECT 'FK_ORPHAN_PFP006M_PDN' AS check_name, COUNT(*) AS violations
FROM PFP006M c
WHERE c.PDN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM PFP001M p WHERE p.PDN = c.PDN);

-- PFP007M.PDN → PFP001M.PDN
SELECT 'FK_ORPHAN_PFP007M_PDN' AS check_name, COUNT(*) AS violations
FROM PFP007M c
WHERE c.PDN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM PFP001M p WHERE p.PDN = c.PDN);

-- PFR003M.RLTD_ACN → DPG001M.ACN
SELECT 'FK_ORPHAN_PFR003M_RLTD_ACN' AS check_name, COUNT(*) AS violations
FROM PFR003M c
WHERE c.RLTD_ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPG001M p WHERE p.ACN = c.RLTD_ACN);

-- PFC008M.ACN → DPG001M.ACN
SELECT 'FK_ORPHAN_PFC008M_ACN' AS check_name, COUNT(*) AS violations
FROM PFC008M c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPG001M p WHERE p.ACN = c.ACN);

-- DPG002M.ACN → DPG001M.ACN
SELECT 'FK_ORPHAN_DPG002M_ACN' AS check_name, COUNT(*) AS violations
FROM DPG002M c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPG001M p WHERE p.ACN = c.ACN);

-- DPG003M.ACN → DPG001M.ACN
SELECT 'FK_ORPHAN_DPG003M_ACN' AS check_name, COUNT(*) AS violations
FROM DPG003M c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPG001M p WHERE p.ACN = c.ACN);

-- DPG004M.ACN → DPG001M.ACN
SELECT 'FK_ORPHAN_DPG004M_ACN' AS check_name, COUNT(*) AS violations
FROM DPG004M c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPG001M p WHERE p.ACN = c.ACN);

-- CMI002H.MDFC_EMN → CMI007M.EMN
SELECT 'FK_ORPHAN_CMI002H_MDFC_EMN' AS check_name, COUNT(*) AS violations
FROM CMI002H c
WHERE c.MDFC_EMN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI007M p WHERE p.EMN = c.MDFC_EMN);

-- CMI002H.APPR_EMN → CMI007M.EMN
SELECT 'FK_ORPHAN_CMI002H_APPR_EMN' AS check_name, COUNT(*) AS violations
FROM CMI002H c
WHERE c.APPR_EMN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI007M p WHERE p.EMN = c.APPR_EMN);

-- CMI008H.EMN → CMI007M.EMN
SELECT 'FK_ORPHAN_CMI008H_EMN' AS check_name, COUNT(*) AS violations
FROM CMI008H c
WHERE c.EMN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI007M p WHERE p.EMN = c.EMN);

-- CMI008H.APPR_EMN → CMI007M.EMN
SELECT 'FK_ORPHAN_CMI008H_APPR_EMN' AS check_name, COUNT(*) AS violations
FROM CMI008H c
WHERE c.APPR_EMN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI007M p WHERE p.EMN = c.APPR_EMN);

-- CMI009M.EMN → CMI007M.EMN
SELECT 'FK_ORPHAN_CMI009M_EMN' AS check_name, COUNT(*) AS violations
FROM CMI009M c
WHERE c.EMN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CMI007M p WHERE p.EMN = c.EMN);

-- LNB002M.LON_NO → LNB001M.LON_NO
SELECT 'FK_ORPHAN_LNB002M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNB002M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNB001M p WHERE p.LON_NO = c.LON_NO);

-- LNB003P.LON_NO → LNB001M.LON_NO
SELECT 'FK_ORPHAN_LNB003P_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNB003P c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNB001M p WHERE p.LON_NO = c.LON_NO);

-- LNB004P.LON_NO → LNB001M.LON_NO
SELECT 'FK_ORPHAN_LNB004P_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNB004P c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNB001M p WHERE p.LON_NO = c.LON_NO);

-- LNB005L.LON_NO → LNB001M.LON_NO
SELECT 'FK_ORPHAN_LNB005L_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNB005L c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNB001M p WHERE p.LON_NO = c.LON_NO);

-- LNB006M.LON_NO → LNB001M.LON_NO
SELECT 'FK_ORPHAN_LNB006M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNB006M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNB001M p WHERE p.LON_NO = c.LON_NO);

-- DPB015M.CARD_NO_ALTR → CLN002M.CARD_NO_ALTR
SELECT 'FK_ORPHAN_DPB015M_CARD_NO_ALTR' AS check_name, COUNT(*) AS violations
FROM DPB015M c
WHERE c.CARD_NO_ALTR IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN002M p WHERE p.CARD_NO_ALTR = c.CARD_NO_ALTR);

-- CLN004L.CARD_NO_ALTR → CLN002M.CARD_NO_ALTR
SELECT 'FK_ORPHAN_CLN004L_CARD_NO_ALTR' AS check_name, COUNT(*) AS violations
FROM CLN004L c
WHERE c.CARD_NO_ALTR IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN002M p WHERE p.CARD_NO_ALTR = c.CARD_NO_ALTR);

-- CLN006L.CARD_NO_ALTR → CLN002M.CARD_NO_ALTR
SELECT 'FK_ORPHAN_CLN006L_CARD_NO_ALTR' AS check_name, COUNT(*) AS violations
FROM CLN006L c
WHERE c.CARD_NO_ALTR IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN002M p WHERE p.CARD_NO_ALTR = c.CARD_NO_ALTR);

-- CLN006L.NEW_CARD_NO → CLN002M.CARD_NO_ALTR
SELECT 'FK_ORPHAN_CLN006L_NEW_CARD_NO' AS check_name, COUNT(*) AS violations
FROM CLN006L c
WHERE c.NEW_CARD_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN002M p WHERE p.CARD_NO_ALTR = c.NEW_CARD_NO);

-- CLN007M.CARD_NO_ALTR → CLN002M.CARD_NO_ALTR
SELECT 'FK_ORPHAN_CLN007M_CARD_NO_ALTR' AS check_name, COUNT(*) AS violations
FROM CLN007M c
WHERE c.CARD_NO_ALTR IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN002M p WHERE p.CARD_NO_ALTR = c.CARD_NO_ALTR);

-- RPC005L.PEN_NO → RPC001M.PEN_NO
SELECT 'FK_ORPHAN_RPC005L_PEN_NO' AS check_name, COUNT(*) AS violations
FROM RPC005L c
WHERE c.PEN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM RPC001M p WHERE p.PEN_NO = c.PEN_NO);

-- RPC006M.PEN_NO → RPC001M.PEN_NO
SELECT 'FK_ORPHAN_RPC006M_PEN_NO' AS check_name, COUNT(*) AS violations
FROM RPC006M c
WHERE c.PEN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM RPC001M p WHERE p.PEN_NO = c.PEN_NO);

-- RPC007L.PEN_NO → RPC001M.PEN_NO
SELECT 'FK_ORPHAN_RPC007L_PEN_NO' AS check_name, COUNT(*) AS violations
FROM RPC007L c
WHERE c.PEN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM RPC001M p WHERE p.PEN_NO = c.PEN_NO);

-- RPC008M.PEN_NO → RPC001M.PEN_NO
SELECT 'FK_ORPHAN_RPC008M_PEN_NO' AS check_name, COUNT(*) AS violations
FROM RPC008M c
WHERE c.PEN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM RPC001M p WHERE p.PEN_NO = c.PEN_NO);

-- RPC009L.PEN_NO → RPC001M.PEN_NO
SELECT 'FK_ORPHAN_RPC009L_PEN_NO' AS check_name, COUNT(*) AS violations
FROM RPC009L c
WHERE c.PEN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM RPC001M p WHERE p.PEN_NO = c.PEN_NO);

-- LNB022M.COLLTR_NO → LNM001M.COLLTR_NO
SELECT 'FK_ORPHAN_LNB022M_COLLTR_NO' AS check_name, COUNT(*) AS violations
FROM LNB022M c
WHERE c.COLLTR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNM001M p WHERE p.COLLTR_NO = c.COLLTR_NO);

-- LNM002M.COLLTR_NO → LNM001M.COLLTR_NO
SELECT 'FK_ORPHAN_LNM002M_COLLTR_NO' AS check_name, COUNT(*) AS violations
FROM LNM002M c
WHERE c.COLLTR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNM001M p WHERE p.COLLTR_NO = c.COLLTR_NO);

-- LNM003M.COLLTR_NO → LNM001M.COLLTR_NO
SELECT 'FK_ORPHAN_LNM003M_COLLTR_NO' AS check_name, COUNT(*) AS violations
FROM LNM003M c
WHERE c.COLLTR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNM001M p WHERE p.COLLTR_NO = c.COLLTR_NO);

-- LNM004M.COLLTR_NO → LNM001M.COLLTR_NO
SELECT 'FK_ORPHAN_LNM004M_COLLTR_NO' AS check_name, COUNT(*) AS violations
FROM LNM004M c
WHERE c.COLLTR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNM001M p WHERE p.COLLTR_NO = c.COLLTR_NO);

-- LNM005M.COLLTR_NO → LNM001M.COLLTR_NO
SELECT 'FK_ORPHAN_LNM005M_COLLTR_NO' AS check_name, COUNT(*) AS violations
FROM LNM005M c
WHERE c.COLLTR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNM001M p WHERE p.COLLTR_NO = c.COLLTR_NO);

-- LNK002M.LON_NO → LNK001M.LON_NO
SELECT 'FK_ORPHAN_LNK002M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNK002M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNK001M p WHERE p.LON_NO = c.LON_NO);

-- LNK003M.LON_NO → LNK001M.LON_NO
SELECT 'FK_ORPHAN_LNK003M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNK003M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNK001M p WHERE p.LON_NO = c.LON_NO);

-- LNK004M.LON_NO → LNK001M.LON_NO
SELECT 'FK_ORPHAN_LNK004M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNK004M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNK001M p WHERE p.LON_NO = c.LON_NO);

-- LNK005M.LON_NO → LNK001M.LON_NO
SELECT 'FK_ORPHAN_LNK005M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNK005M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNK001M p WHERE p.LON_NO = c.LON_NO);

-- LNK006M.LON_NO → LNK001M.LON_NO
SELECT 'FK_ORPHAN_LNK006M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNK006M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNK001M p WHERE p.LON_NO = c.LON_NO);

-- CLN002M.MBR_NO → CLN001M.MBR_NO
SELECT 'FK_ORPHAN_CLN002M_MBR_NO' AS check_name, COUNT(*) AS violations
FROM CLN002M c
WHERE c.MBR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN001M p WHERE p.MBR_NO = c.MBR_NO);

-- CLN012M.MBR_NO → CLN001M.MBR_NO
SELECT 'FK_ORPHAN_CLN012M_MBR_NO' AS check_name, COUNT(*) AS violations
FROM CLN012M c
WHERE c.MBR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN001M p WHERE p.MBR_NO = c.MBR_NO);

-- CLN013L.MBR_NO → CLN001M.MBR_NO
SELECT 'FK_ORPHAN_CLN013L_MBR_NO' AS check_name, COUNT(*) AS violations
FROM CLN013L c
WHERE c.MBR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN001M p WHERE p.MBR_NO = c.MBR_NO);

-- CLN015M.MBR_NO → CLN001M.MBR_NO
SELECT 'FK_ORPHAN_CLN015M_MBR_NO' AS check_name, COUNT(*) AS violations
FROM CLN015M c
WHERE c.MBR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN001M p WHERE p.MBR_NO = c.MBR_NO);

-- CLN018M.MBR_NO → CLN001M.MBR_NO
SELECT 'FK_ORPHAN_CLN018M_MBR_NO' AS check_name, COUNT(*) AS violations
FROM CLN018M c
WHERE c.MBR_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CLN001M p WHERE p.MBR_NO = c.MBR_NO);

-- SLE001L.MERCH_NO → SLE021M.MERCH_NO
SELECT 'FK_ORPHAN_SLE001L_MERCH_NO' AS check_name, COUNT(*) AS violations
FROM SLE001L c
WHERE c.MERCH_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE021M p WHERE p.MERCH_NO = c.MERCH_NO);

-- SLE002L.MERCH_NO → SLE021M.MERCH_NO
SELECT 'FK_ORPHAN_SLE002L_MERCH_NO' AS check_name, COUNT(*) AS violations
FROM SLE002L c
WHERE c.MERCH_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE021M p WHERE p.MERCH_NO = c.MERCH_NO);

-- SLE013L.MERCH_NO → SLE021M.MERCH_NO
SELECT 'FK_ORPHAN_SLE013L_MERCH_NO' AS check_name, COUNT(*) AS violations
FROM SLE013L c
WHERE c.MERCH_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE021M p WHERE p.MERCH_NO = c.MERCH_NO);

-- SLE022M.MERCH_NO → SLE021M.MERCH_NO
SELECT 'FK_ORPHAN_SLE022M_MERCH_NO' AS check_name, COUNT(*) AS violations
FROM SLE022M c
WHERE c.MERCH_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE021M p WHERE p.MERCH_NO = c.MERCH_NO);

-- SLE023M.MERCH_NO → SLE021M.MERCH_NO
SELECT 'FK_ORPHAN_SLE023M_MERCH_NO' AS check_name, COUNT(*) AS violations
FROM SLE023M c
WHERE c.MERCH_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE021M p WHERE p.MERCH_NO = c.MERCH_NO);

-- LNH002M.LON_NO → LNH001M.LON_NO
SELECT 'FK_ORPHAN_LNH002M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNH002M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNH001M p WHERE p.LON_NO = c.LON_NO);

-- LNH003M.LON_NO → LNH001M.LON_NO
SELECT 'FK_ORPHAN_LNH003M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNH003M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNH001M p WHERE p.LON_NO = c.LON_NO);

-- LNH004M.LON_NO → LNH001M.LON_NO
SELECT 'FK_ORPHAN_LNH004M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNH004M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNH001M p WHERE p.LON_NO = c.LON_NO);

-- LNH005M.LON_NO → LNH001M.LON_NO
SELECT 'FK_ORPHAN_LNH005M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNH005M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNH001M p WHERE p.LON_NO = c.LON_NO);

-- LNH006M.LON_NO → LNH001M.LON_NO
SELECT 'FK_ORPHAN_LNH006M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNH006M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNH001M p WHERE p.LON_NO = c.LON_NO);

-- LNW002M.LON_NO → LNW001M.LON_NO
SELECT 'FK_ORPHAN_LNW002M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNW002M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNW001M p WHERE p.LON_NO = c.LON_NO);

-- LNW003M.LON_NO → LNW001M.LON_NO
SELECT 'FK_ORPHAN_LNW003M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNW003M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNW001M p WHERE p.LON_NO = c.LON_NO);

-- LNW004M.LON_NO → LNW001M.LON_NO
SELECT 'FK_ORPHAN_LNW004M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNW004M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNW001M p WHERE p.LON_NO = c.LON_NO);

-- LNW005M.LON_NO → LNW001M.LON_NO
SELECT 'FK_ORPHAN_LNW005M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNW005M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNW001M p WHERE p.LON_NO = c.LON_NO);

-- LNW006M.LON_NO → LNW001M.LON_NO
SELECT 'FK_ORPHAN_LNW006M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNW006M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNW001M p WHERE p.LON_NO = c.LON_NO);

-- LNO002L.LON_NO → LNO001M.LON_NO
SELECT 'FK_ORPHAN_LNO002L_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNO002L c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNO001M p WHERE p.LON_NO = c.LON_NO);

-- LNO003L.LON_NO → LNO001M.LON_NO
SELECT 'FK_ORPHAN_LNO003L_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNO003L c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNO001M p WHERE p.LON_NO = c.LON_NO);

-- LNO004L.LON_NO → LNO001M.LON_NO
SELECT 'FK_ORPHAN_LNO004L_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNO004L c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNO001M p WHERE p.LON_NO = c.LON_NO);

-- LNO005M.LON_NO → LNO001M.LON_NO
SELECT 'FK_ORPHAN_LNO005M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNO005M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNO001M p WHERE p.LON_NO = c.LON_NO);

-- LNO006L.LON_NO → LNO001M.LON_NO
SELECT 'FK_ORPHAN_LNO006L_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNO006L c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNO001M p WHERE p.LON_NO = c.LON_NO);

-- DPF002M.ACN → DPF001M.ACN
SELECT 'FK_ORPHAN_DPF002M_ACN' AS check_name, COUNT(*) AS violations
FROM DPF002M c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPF001M p WHERE p.ACN = c.ACN);

-- DPF003P.ACN → DPF001M.ACN
SELECT 'FK_ORPHAN_DPF003P_ACN' AS check_name, COUNT(*) AS violations
FROM DPF003P c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPF001M p WHERE p.ACN = c.ACN);

-- DPF004P.ACN → DPF001M.ACN
SELECT 'FK_ORPHAN_DPF004P_ACN' AS check_name, COUNT(*) AS violations
FROM DPF004P c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPF001M p WHERE p.ACN = c.ACN);

-- DPF005L.ACN → DPF001M.ACN
SELECT 'FK_ORPHAN_DPF005L_ACN' AS check_name, COUNT(*) AS violations
FROM DPF005L c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPF001M p WHERE p.ACN = c.ACN);

-- DPF006H.ACN → DPF001M.ACN
SELECT 'FK_ORPHAN_DPF006H_ACN' AS check_name, COUNT(*) AS violations
FROM DPF006H c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPF001M p WHERE p.ACN = c.ACN);

-- LNJ002M.LON_NO → LNJ001M.LON_NO
SELECT 'FK_ORPHAN_LNJ002M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNJ002M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNJ001M p WHERE p.LON_NO = c.LON_NO);

-- LNJ003M.LON_NO → LNJ001M.LON_NO
SELECT 'FK_ORPHAN_LNJ003M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNJ003M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNJ001M p WHERE p.LON_NO = c.LON_NO);

-- LNJ004L.LON_NO → LNJ001M.LON_NO
SELECT 'FK_ORPHAN_LNJ004L_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNJ004L c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNJ001M p WHERE p.LON_NO = c.LON_NO);

-- LNJ005M.LON_NO → LNJ001M.LON_NO
SELECT 'FK_ORPHAN_LNJ005M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNJ005M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNJ001M p WHERE p.LON_NO = c.LON_NO);

-- LNJ006M.LON_NO → LNJ001M.LON_NO
SELECT 'FK_ORPHAN_LNJ006M_LON_NO' AS check_name, COUNT(*) AS violations
FROM LNJ006M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM LNJ001M p WHERE p.LON_NO = c.LON_NO);

-- SLE003L.TRN_NO → SLE001L.TRN_NO
SELECT 'FK_ORPHAN_SLE003L_TRN_NO' AS check_name, COUNT(*) AS violations
FROM SLE003L c
WHERE c.TRN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE001L p WHERE p.TRN_NO = c.TRN_NO);

-- SLE004L.TRN_NO → SLE001L.TRN_NO
SELECT 'FK_ORPHAN_SLE004L_TRN_NO' AS check_name, COUNT(*) AS violations
FROM SLE004L c
WHERE c.TRN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE001L p WHERE p.TRN_NO = c.TRN_NO);

-- SLE005L.TRN_NO → SLE001L.TRN_NO
SELECT 'FK_ORPHAN_SLE005L_TRN_NO' AS check_name, COUNT(*) AS violations
FROM SLE005L c
WHERE c.TRN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE001L p WHERE p.TRN_NO = c.TRN_NO);

-- SLE006L.TRN_NO → SLE001L.TRN_NO
SELECT 'FK_ORPHAN_SLE006L_TRN_NO' AS check_name, COUNT(*) AS violations
FROM SLE006L c
WHERE c.TRN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE001L p WHERE p.TRN_NO = c.TRN_NO);

-- SLE007L.TRN_NO → SLE001L.TRN_NO
SELECT 'FK_ORPHAN_SLE007L_TRN_NO' AS check_name, COUNT(*) AS violations
FROM SLE007L c
WHERE c.TRN_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SLE001L p WHERE p.TRN_NO = c.TRN_NO);

-- FXR002M.LON_NO → FXR001M.LON_NO
SELECT 'FK_ORPHAN_FXR002M_LON_NO' AS check_name, COUNT(*) AS violations
FROM FXR002M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM FXR001M p WHERE p.LON_NO = c.LON_NO);

-- FXR003M.LON_NO → FXR001M.LON_NO
SELECT 'FK_ORPHAN_FXR003M_LON_NO' AS check_name, COUNT(*) AS violations
FROM FXR003M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM FXR001M p WHERE p.LON_NO = c.LON_NO);

-- FXR004M.LON_NO → FXR001M.LON_NO
SELECT 'FK_ORPHAN_FXR004M_LON_NO' AS check_name, COUNT(*) AS violations
FROM FXR004M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM FXR001M p WHERE p.LON_NO = c.LON_NO);

-- FXR005M.LON_NO → FXR001M.LON_NO
SELECT 'FK_ORPHAN_FXR005M_LON_NO' AS check_name, COUNT(*) AS violations
FROM FXR005M c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM FXR001M p WHERE p.LON_NO = c.LON_NO);

-- FXR006L.LON_NO → FXR001M.LON_NO
SELECT 'FK_ORPHAN_FXR006L_LON_NO' AS check_name, COUNT(*) AS violations
FROM FXR006L c
WHERE c.LON_NO IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM FXR001M p WHERE p.LON_NO = c.LON_NO);

-- DPN002M.ACN → DPN001M.ACN
SELECT 'FK_ORPHAN_DPN002M_ACN' AS check_name, COUNT(*) AS violations
FROM DPN002M c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPN001M p WHERE p.ACN = c.ACN);

-- DPN003M.ACN → DPN001M.ACN
SELECT 'FK_ORPHAN_DPN003M_ACN' AS check_name, COUNT(*) AS violations
FROM DPN003M c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPN001M p WHERE p.ACN = c.ACN);

-- DPN004P.ACN → DPN001M.ACN
SELECT 'FK_ORPHAN_DPN004P_ACN' AS check_name, COUNT(*) AS violations
FROM DPN004P c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPN001M p WHERE p.ACN = c.ACN);

-- DPN005L.ACN → DPN001M.ACN
SELECT 'FK_ORPHAN_DPN005L_ACN' AS check_name, COUNT(*) AS violations
FROM DPN005L c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPN001M p WHERE p.ACN = c.ACN);

-- DPN006M.ACN → DPN001M.ACN
SELECT 'FK_ORPHAN_DPN006M_ACN' AS check_name, COUNT(*) AS violations
FROM DPN006M c
WHERE c.ACN IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DPN001M p WHERE p.ACN = c.ACN);

-- 2.2 Deferred FK 2-pass 완료 여부 확인

-- AML002L.SRC_CSK_STR_NO → CSK008L
SELECT 'DEFERRED_FK_AML002L_SRC_CSK_STR_NO' AS check_name,
       COUNT(*) FILTER (WHERE SRC_CSK_STR_NO IS NULL) AS null_count,
       COUNT(*) AS total
FROM AML002L;

-- AML003L.SRC_CSK_CTR_NO → CSK009L
SELECT 'DEFERRED_FK_AML003L_SRC_CSK_CTR_NO' AS check_name,
       COUNT(*) FILTER (WHERE SRC_CSK_CTR_NO IS NULL) AS null_count,
       COUNT(*) AS total
FROM AML003L;

-- PFP001M.CURR_VER → PFP014M
SELECT 'DEFERRED_FK_PFP001M_CURR_VER' AS check_name,
       COUNT(*) FILTER (WHERE CURR_VER IS NULL) AS null_count,
       COUNT(*) AS total
FROM PFP001M;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 3. 날짜 순서 제약 (date_order)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- csc001m_date_01: 출생일 ≤ 고객 신규일
SELECT 'csc001m_date_01' AS check_name, COUNT(*) AS violations
FROM CSC001M
WHERE NOT (BRTH_YMD <= NEW_YMD);

-- csc001m_date_02: 신규일 < 해지일
SELECT 'csc001m_date_02' AS check_name, COUNT(*) AS violations
FROM CSC001M
WHERE (CSCLS_YMD IS NOT NULL) AND NOT (NEW_YMD < CSCLS_YMD);

-- dpg001m_date_01: 계좌 개설일은 현재 기준 이전
SELECT 'dpg001m_date_01' AS check_name, COUNT(*) AS violations
FROM DPG001M
WHERE NOT (NEW_YMD <= ETCL_BASE_YMD);

-- dpg001m_date_02: 개설일 ≤ 만기일
SELECT 'dpg001m_date_02' AS check_name, COUNT(*) AS violations
FROM DPG001M
WHERE (EXPR_YMD IS NOT NULL) AND NOT (NEW_YMD <= EXPR_YMD);

-- dpg001m_date_03: 개설일 ≤ 해지일
SELECT 'dpg001m_date_03' AS check_name, COUNT(*) AS violations
FROM DPG001M
WHERE (CLS_YMD IS NOT NULL) AND NOT (NEW_YMD <= CLS_YMD);

-- dpf001m_date_01: 정기예금 개설일 < 만기일
SELECT 'dpf001m_date_01' AS check_name, COUNT(*) AS violations
FROM DPF001M
WHERE NOT (OPEN_YMD < MAT_YMD);

-- lnb001m_date_01: 신청일 ≤ 승인일
SELECT 'lnb001m_date_01' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE NOT (APLY_YMD <= APPR_YMD);

-- lnb001m_date_02: 승인일 ≤ 실행일
SELECT 'lnb001m_date_02' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE NOT (APPR_YMD <= EXEC_YMD);

-- lnb001m_date_03: 실행일 < 만기일
SELECT 'lnb001m_date_03' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE NOT (EXEC_YMD < MAT_YMD);

-- lnb001m_date_04: 완제일은 실행일 이후
SELECT 'lnb001m_date_04' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE (FULL_RPY_YMD IS NOT NULL) AND NOT (EXEC_YMD <= FULL_RPY_YMD);

-- lnh002m_date_01: 신청 ≤ 의사결정
SELECT 'lnh002m_date_01' AS check_name, COUNT(*) AS violations
FROM LNH002M
WHERE NOT (APLY_YMD <= DECID_YMD);

-- lno001m_date_01: 연체 시작일 ≥ 대출 실행일 (다른 테이블)
SELECT 'lno001m_date_01' AS check_name, COUNT(*) AS violations
FROM LNO001M
WHERE NOT (OVDU_STRT_YMD >= EXEC_YMD);

-- lno001m_date_02: 연체 시작 ≤ 종료
SELECT 'lno001m_date_02' AS check_name, COUNT(*) AS violations
FROM LNO001M
WHERE (OVDU_END_YMD IS NOT NULL) AND NOT (OVDU_STRT_YMD <= OVDU_END_YMD);

-- cln001m_date_01: 카드회원 가입일 ≤ 현재
SELECT 'cln001m_date_01' AS check_name, COUNT(*) AS violations
FROM CLN001M
WHERE NOT (JOIN_YMD <= ETCL_BASE_YMD);

-- cln002m_date_01: 카드 발급일 ≤ 유효기간
SELECT 'cln002m_date_01' AS check_name, COUNT(*) AS violations
FROM CLN002M
WHERE NOT (ISS_YMD <= EXPR_YMD);

-- cln002m_date_02: 발급일 ≤ 해지일
SELECT 'cln002m_date_02' AS check_name, COUNT(*) AS violations
FROM CLN002M
WHERE (CNCL_YMD IS NOT NULL) AND NOT (ISS_YMD <= CNCL_YMD);

-- sle001l_date_01: 매출 발생일 ≤ 현재
SELECT 'sle001l_date_01' AS check_name, COUNT(*) AS violations
FROM SLE001L
WHERE NOT (TRN_YMD <= ETCL_BASE_YMD);

-- rpc001m_date_01: 
SELECT 'rpc001m_date_01' AS check_name, COUNT(*) AS violations
FROM RPC001M
WHERE NOT (JOIN_YMD <= ETCL_BASE_YMD);

-- rpc013l_date_01: 연금 수령 개시일 (과거 또는 미래 모두 가능)
SELECT 'rpc013l_date_01' AS check_name, COUNT(*) AS violations
FROM RPC013L
WHERE NOT (PAY_STRT_YMD <= ETCL_BASE_YMD OR PAY_STRT_YMD >= ETCL_BASE_YMD);

-- trs001m_date_01: 
SELECT 'trs001m_date_01' AS check_name, COUNT(*) AS violations
FROM TRS001M
WHERE NOT (CONTRACT_YMD <= MAT_YMD);

-- trs001m_date_02: 
SELECT 'trs001m_date_02' AS check_name, COUNT(*) AS violations
FROM TRS001M
WHERE (TERM_YMD IS NOT NULL) AND NOT (CONTRACT_YMD <= TERM_YMD);

-- fxc003l_date_01: 송금 신청 ≤ 결제일
SELECT 'fxc003l_date_01' AS check_name, COUNT(*) AS violations
FROM FXC003L
WHERE NOT (REQ_YMD <= SETTLE_YMD);

-- fxc021m_date_01: LC 개설 ≤ 만기
SELECT 'fxc021m_date_01' AS check_name, COUNT(*) AS violations
FROM FXC021M
WHERE NOT (ISS_YMD <= EXPR_YMD);

-- ebs001l_date_01: 이체 시각 ≤ ETL 시각
SELECT 'ebs001l_date_01' AS check_name, COUNT(*) AS violations
FROM EBS001L
WHERE NOT (TRN_TS <= ETCL_JOB_TS);

-- drv001m_date_01: 
SELECT 'drv001m_date_01' AS check_name, COUNT(*) AS violations
FROM DRV001M
WHERE NOT (TRADE_YMD <= MAT_YMD);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 4. 금액 범위·관계 제약 (amount)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- lnb001m_amt_01: 
SELECT 'lnb001m_amt_01' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE NOT (LON_BAL >= 0);

-- lnb001m_amt_02: 잔액은 실행금액 이하
SELECT 'lnb001m_amt_02' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE NOT (LON_BAL <= LN_AMT);

-- lnb001m_amt_03: 누적이자 음수 불가
SELECT 'lnb001m_amt_03' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE NOT (INT_AMT_ACCU >= 0);

-- lnb001m_amt_04: 
SELECT 'lnb001m_amt_04' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE NOT (LN_AMT > 0);

-- dpg001m_amt_01: 예금 잔액 음수 불가 (마이너스 통장 제외)
SELECT 'dpg001m_amt_01' AS check_name, COUNT(*) AS violations
FROM DPG001M
WHERE NOT (BAL >= 0);

-- dpf001m_amt_01: 만기 도래 정기예금 잔액 ≥ 초기 가입금액 (이자 가산)
SELECT 'dpf001m_amt_01' AS check_name, COUNT(*) AS violations
FROM DPF001M
WHERE (STATUS_CD = '02') AND NOT (BAL >= INIT_AMT);

-- lno001m_amt_01: 
SELECT 'lno001m_amt_01' AS check_name, COUNT(*) AS violations
FROM LNO001M
WHERE NOT (OVDU_PRN_AMT >= 0 AND OVDU_INT_AMT >= 0);

-- lno001m_amt_02: 연체 원금 ≤ 대출 잔액 [cross-table]
SELECT 'lno001m_amt_02' AS check_name, COUNT(*) AS violations
FROM LNO001M a JOIN LNB001M b USING (LON_NO)
WHERE NOT (LNO001M.OVDU_PRN_AMT <= LNB001M.LON_BAL);

-- lno007l_amt_01: 상각액 ≤ 대출 잔액 [cross-table]
SELECT 'lno007l_amt_01' AS check_name, COUNT(*) AS violations
FROM LNO007L a JOIN LNB001M b USING (LON_NO)
WHERE NOT (LNO007L.WRITE_OFF_AMT <= LNB001M.LON_BAL);

-- lno008m_amt_01: 회수금 ≤ 상각금 [cross-table]
SELECT 'lno008m_amt_01' AS check_name, COUNT(*) AS violations
FROM LNO008M a JOIN LNO007L b USING (LON_NO)
WHERE NOT (LNO008M.RECOV_AMT <= LNO007L.WRITE_OFF_AMT);

-- cln002m_amt_01: 
SELECT 'cln002m_amt_01' AS check_name, COUNT(*) AS violations
FROM CLN002M
WHERE NOT (CARD_LIM > 0);

-- cln002m_amt_02: 현재 사용액 ≤ 한도
SELECT 'cln002m_amt_02' AS check_name, COUNT(*) AS violations
FROM CLN002M
WHERE NOT (CUR_USE_AMT <= CARD_LIM);

-- sle001l_amt_01: 
SELECT 'sle001l_amt_01' AS check_name, COUNT(*) AS violations
FROM SLE001L
WHERE NOT (TRN_AMT > 0);

-- sle001l_amt_02: 할부 2~36개월
SELECT 'sle001l_amt_02' AS check_name, COUNT(*) AS violations
FROM SLE001L
WHERE (TRN_TCD = '03') AND NOT (INSTL_MTH BETWEEN 2 AND 36);

-- rpc008m_amt_01: 연금 납입 한도 연 900만원 (세액공제 대상)
SELECT 'rpc008m_amt_01' AS check_name, COUNT(*) AS violations
FROM RPC008M
WHERE NOT (ANNUAL_PAID <= 9000000);

-- rpd002m_amt_01: IRP 납입 연 1,800만원 한도
SELECT 'rpd002m_amt_01' AS check_name, COUNT(*) AS violations
FROM RPD002M
WHERE NOT (ANNUAL_PAID <= 18000000);

-- fxc017l_amt_01: 지급수단 신고는 USD 5,000 이상
SELECT 'fxc017l_amt_01' AS check_name, COUNT(*) AS violations
FROM FXC017L
WHERE (RPT_TCD = '04') AND NOT (USD_AMT >= 5000);

-- ebb011m_amt_01: 일한도 ≥ 1회한도
SELECT 'ebb011m_amt_01' AS check_name, COUNT(*) AS violations
FROM EBB011M
WHERE NOT (DAY_LIM >= TRN_LIM);

-- ebb011m_amt_02: 임시 증액 ≥ 일반 한도
SELECT 'ebb011m_amt_02' AS check_name, COUNT(*) AS violations
FROM EBB011M
WHERE (TEMP_UP_LIM IS NOT NULL) AND NOT (TEMP_UP_LIM >= DAY_LIM);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 5. 상태 전이 제약 (status)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- dpg001m_stat_01: 해지 계좌는 해지일 필수
SELECT 'dpg001m_stat_01' AS check_name, COUNT(*) AS violations
FROM DPG001M
WHERE (LDGR_SCD = '04') AND NOT (CLS_YMD IS NOT NULL);

-- dpg001m_stat_02: 활성 계좌는 해지일 NULL
SELECT 'dpg001m_stat_02' AS check_name, COUNT(*) AS violations
FROM DPG001M
WHERE (LDGR_SCD IN ('01','02','03')) AND NOT (CLS_YMD IS NULL);

-- dpg001m_stat_03: 해지 계좌 잔액 0
SELECT 'dpg001m_stat_03' AS check_name, COUNT(*) AS violations
FROM DPG001M
WHERE (LDGR_SCD = '04') AND NOT (BAL = 0);

-- lnb001m_stat_01: 
SELECT 'lnb001m_stat_01' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE (STATUS_CD = '05') AND NOT (LON_BAL = 0 AND FULL_RPY_YMD IS NOT NULL);

-- lnb001m_stat_02: 
SELECT 'lnb001m_stat_02' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE (STATUS_CD IN ('01','02','03','04')) AND NOT (FULL_RPY_YMD IS NULL);

-- cln002m_stat_01: 
SELECT 'cln002m_stat_01' AS check_name, COUNT(*) AS violations
FROM CLN002M
WHERE (CARD_STAT_CD = '04') AND NOT (CNCL_YMD IS NOT NULL AND CUR_USE_AMT = 0);

-- cln002m_stat_02: 
SELECT 'cln002m_stat_02' AS check_name, COUNT(*) AS violations
FROM CLN002M
WHERE (CARD_STAT_CD = '02') AND NOT (STOP_YMD IS NOT NULL);

-- lno001m_stat_01: 정상화된 연체는 종료일 + 원금 0
SELECT 'lno001m_stat_01' AS check_name, COUNT(*) AS violations
FROM LNO001M
WHERE (STATUS_CD = '99') AND NOT (OVDU_END_YMD IS NOT NULL AND OVDU_PRN_AMT = 0);

-- rpc013l_stat_01: 
SELECT 'rpc013l_stat_01' AS check_name, COUNT(*) AS violations
FROM RPC013L
WHERE (PAY_STAT = '02') AND NOT (PAY_STRT_YMD IS NOT NULL);

-- fxc021m_stat_01: 
SELECT 'fxc021m_stat_01' AS check_name, COUNT(*) AS violations
FROM FXC021M
WHERE (LC_STATUS = '04') AND NOT (ISS_YMD IS NOT NULL AND EXPR_YMD >= ISS_YMD);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 6. 크로스 테이블 정합성 (cross_table)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- dpf_bal_consistency: 정기예금 현잔액 = 일별잔액 최신값
-- Tables: DPF001M, DPF003P
-- Expected: DPF001M.BAL = (SELECT MAX(BAL) FROM DPF003P WHERE ACN = DPF001M.ACN AND BASE_YMD = (SELECT MAX(BASE_YMD) FROM DPF003P WHERE ACN = DPF001M.ACN))
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- lnb_ovdue_consistency: 대출 잔액 = 연체 원금 + 정상 잔액
-- Tables: LNB001M, LNO001M
-- Expected: LNB001M.LON_BAL = LNO001M.OVDU_PRN_AMT + LNB001M.NORMAL_BAL
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- cln_member_card_consistency: 활성 회원은 카드 1장 이상
-- Tables: CLN001M, CLN002M
-- Expected: COUNT(CLN002M.CARD_NO_ALTR WHERE CLN002M.MBR_NO = CLN001M.MBR_NO) >= 1
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- str_aml_consistency: CSK에서 FIU 이관 플래그 Y면 AML에 이관 레코드 있어야
-- Tables: CSK008L, AML002L
-- Expected: CSK008L.ESCL_AML_YN = 'Y' → EXISTS (AML002L WHERE AML002L.SRC_CSK_STR_NO = CSK008L.STR_NO)
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- ctr_aml_consistency: 
-- Tables: CSK009L, AML003L
-- Expected: CSK009L.ESCL_AML_YN = 'Y' → EXISTS (AML003L WHERE AML003L.SRC_CSK_CTR_NO = CSK009L.CTR_NO)
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- fds_fraud_consistency: FDS 확정건 중 일부가 사기피해 신고로 이관
-- Tables: EBS021M, EBS022M
-- Expected: EBS021M.VERDICT_CD = '02' (부정확정) → 일부 비율 EBS022M에 SRC_FDS_NO로 연계
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- mvp_bal_consistency: 부점별 수신 마트 잔액 = 원장 잔액 합
-- Tables: DPG001M, MVP001S
-- Expected: SUM(DPG001M.BAL WHERE MNGM_BRCD = X) = MVP001S.EOD_BAL WHERE BRCD = X AND BASE_YMD = Y
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- mvn_bal_consistency: 
-- Tables: LNB001M, MVN001S
-- Expected: SUM(LNB001M.LON_BAL WHERE EXEC_BRCD = X) = MVN001S.EOD_BAL WHERE BRCD = X
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- card_point_consistency: 포인트 잔액 = 적립 - 사용
-- Tables: CLN002M, SLE001L, CLN030M
-- Expected: CLN030M.POINT_BAL = SUM(earned_points) - SUM(used_points) from ledger
-- [MANUAL VERIFICATION - 복잡한 집계 로직 필요]
-- 예시 쿼리를 각 관계별로 수동 작성 필요.

-- 6.1 정기예금 잔액 정합성 (DPF001M vs DPF003P)
SELECT 'DPF_BAL_CONSISTENCY' AS check_name, COUNT(*) AS violations
FROM DPF001M d
WHERE d.BAL != COALESCE((
    SELECT BAL FROM DPF003P p
    WHERE p.ACN = d.ACN
    ORDER BY BASE_YMD DESC LIMIT 1
), 0);

-- 6.2 STR AML 이관 정합성
SELECT 'STR_AML_CONSISTENCY' AS check_name, COUNT(*) AS violations
FROM CSK008L c
WHERE c.ESCL_AML_YN = 'Y'
  AND NOT EXISTS (SELECT 1 FROM AML002L a WHERE a.SRC_CSK_STR_NO = c.STR_NO);

-- 6.3 CTR AML 이관 정합성
SELECT 'CTR_AML_CONSISTENCY' AS check_name, COUNT(*) AS violations
FROM CSK009L c
WHERE c.ESCL_AML_YN = 'Y'
  AND NOT EXISTS (SELECT 1 FROM AML003L a WHERE a.SRC_CSK_CTR_NO = c.CTR_NO);

-- 6.4 부점 수신 마트 vs 원장 합
SELECT 'MVP_BAL_CONSISTENCY' AS check_name, COUNT(*) AS violations
FROM MVP001S m
JOIN (
    SELECT MNGM_BRCD, SUM(BAL) AS total_bal
    FROM DPG001M
    WHERE LDGR_SCD IN ('01', '02')
    GROUP BY MNGM_BRCD
) d ON m.BRCD = d.MNGM_BRCD
WHERE m.BASE_YMD = (SELECT MAX(BASE_YMD) FROM MVP001S)
  AND ABS(m.EOD_BAL - d.total_bal) > 1;  -- 반올림 오차 허용


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 7. 코드 값 연계 제약 (code)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- csc_corp_01: 법인 고객은 CSC002M에 상세 있어야
SELECT 'csc_corp_01' AS check_name, COUNT(*) AS violations
FROM CSC001M
WHERE (CST_TCD = '03') AND NOT (EXISTS (CSC002M WHERE CSN = CSC001M.CSN));

-- csc_minor_01: 
SELECT 'csc_minor_01' AS check_name, COUNT(*) AS violations
FROM CSC001M
WHERE (BRTH_YMD > DATE_SUB(CURRENT_DATE, INTERVAL 19 YEAR)) AND NOT (CST_TCD = '02');

-- lnb_type_prod_01: 
SELECT 'lnb_type_prod_01' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE (LON_TCD = '01') AND NOT (EXISTS (LNH001M WHERE LON_NO = LNB001M.LON_NO));

-- lnb_type_prod_02: 
SELECT 'lnb_type_prod_02' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE (LON_TCD = '02') AND NOT (EXISTS (LNJ001M WHERE LON_NO = LNB001M.LON_NO));

-- lnb_type_prod_03: 
SELECT 'lnb_type_prod_03' AS check_name, COUNT(*) AS violations
FROM LNB001M
WHERE (LON_TCD = '03') AND NOT (EXISTS (LNC001M WHERE LON_NO = LNB001M.LON_NO));

-- cln_type_01: 
SELECT 'cln_type_01' AS check_name, COUNT(*) AS violations
FROM CLN001M
WHERE (MBR_TCD IN ('01','02','05')) AND NOT (NOT EXISTS (CSC002M WHERE CSN = CLN001M.CSN AND CORP_TCD IS NOT NULL));

-- lno_stage_01: 
SELECT 'lno_stage_01' AS check_name, COUNT(*) AS violations
FROM LNO001M
WHERE (OVDU_DAYS >= 90) AND NOT (STATUS_CD IN ('02','03'));


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 8. 카디널리티 절대 제약 (cardinality)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- cardinality_0072: 주거래 설정은 1개
-- parent=CSC001M, child=CSC034M, condition=MAIN_BANK_YN = 'Y'
-- [MANUAL: FK 컬럼명 확인 후 실행]

-- cardinality_0073: 
SELECT 'cardinality_0073' AS check_name, COUNT(*) AS violations
FROM (
    SELECT CARD_NO_ALTR, CARD_STAT_CD, COUNT(*) AS cnt
    FROM CLN002M WHERE CARD_STAT_CD = '01'
    GROUP BY CARD_NO_ALTR, CARD_STAT_CD
    HAVING COUNT(*) > 1
) x;

-- cardinality_0074: 
SELECT 'cardinality_0074' AS check_name, COUNT(*) AS violations
FROM (
    SELECT ACN, COUNT(*) AS cnt
    FROM DPG001M 
    GROUP BY ACN
    HAVING COUNT(*) > 1
) x;

-- cardinality_0075: 
SELECT 'cardinality_0075' AS check_name, COUNT(*) AS violations
FROM (
    SELECT CSN, COUNT(*) AS cnt
    FROM CSC001M 
    GROUP BY CSN
    HAVING COUNT(*) > 1
) x;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 9. 파생값 관계 (computed)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- 9.1 NPL 잔액 정합성
SELECT 'NPL_COMPUTED' AS check_name, COUNT(*) AS violations
FROM MVN009S m
JOIN (
    SELECT SUM(BAL) AS npl_bal
    FROM RSK022M
    WHERE STAGE IN (2, 3)
) r ON TRUE
WHERE m.BASE_YMD = (SELECT MAX(BASE_YMD) FROM MVN009S)
  AND ABS(m.NPL_BAL - r.npl_bal) > 1;

-- 9.2 FNA029M CIR 범위 검증
SELECT 'CIR_COMPUTED' AS check_name, COUNT(*) AS violations
FROM FNA029M
WHERE CIR IS NOT NULL
  AND (CIR < 0 OR CIR > 200);  -- 비정상 범위

-- 9.3 RPI003M 적립비율
SELECT 'FUND_RTO_COMPUTED' AS check_name, COUNT(*) AS violations
FROM RPI003M
WHERE FUND_RTO IS NOT NULL
  AND (FUND_RTO < 30 OR FUND_RTO > 150);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 10. V2 품질결함 주입 비율 확인 (의도적 위반)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- 10.1 미매칭 FK 비율 (허용 0.5%)
-- 각 FK별 orphan 비율을 합산해 전체 대비 확인
-- [레퍼런스: business_rules.json.quality_defect_tolerances]
SELECT 'MISSING_FK_RATIO' AS check_name,
       'See FK orphan queries above, ratio should be ~0.5%' AS note;

-- 10.2 중복 행 비율 (CSC006M 등 지정 테이블만)
SELECT 'DUPLICATE_ROWS_CSC006M' AS check_name,
       COUNT(*) - COUNT(DISTINCT (CSN, CONTACT_TCD, HP_NO, TEL_NO, EMAIL)) AS dup_count,
       COUNT(*) AS total_rows
FROM CSC006M;

-- 10.3 음수 금액 비율 (허용 0.1%)
SELECT 'NEGATIVE_AMT_SAMPLE' AS check_name,
       SUM(CASE WHEN LN_AMT < 0 THEN 1 ELSE 0 END) AS negatives,
       COUNT(*) AS total
FROM LNB001M;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 11. 주요 컬럼 분포 검증 (통계)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- 11.1 고객 성별 분포 (기대 M 51% / F 49%)
SELECT 'GENDER_DIST' AS check_name, GEN_CD, COUNT(*) AS cnt
FROM CSC001M
GROUP BY GEN_CD;

-- 11.2 대출 상품 타입 분포
SELECT 'LOAN_TYPE_DIST' AS check_name, LON_TCD, COUNT(*) AS cnt
FROM LNB001M
GROUP BY LON_TCD
ORDER BY LON_TCD;

-- 11.3 카드 매출 금액 분포 (lognormal 평균 50,000)
SELECT 'SLE_AMT_DIST' AS check_name,
       MIN(TRN_AMT), MAX(TRN_AMT), AVG(TRN_AMT), STDDEV(TRN_AMT),
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY TRN_AMT) AS median
FROM SLE001L;

-- 11.4 외화 통화 분포 (기대 USD 18%, JPY 6%, ...)
SELECT 'FX_CCY_DIST' AS check_name, CCY_CD, COUNT(*) AS cnt
FROM DPY001M
GROUP BY CCY_CD
ORDER BY cnt DESC;

-- 11.5 부점별 고객 분포 (편향 체크)
SELECT 'BRANCH_CUSTOMER_DIST' AS check_name, MAIN_BRCD, COUNT(*) AS cnt
FROM CSC001M
GROUP BY MAIN_BRCD
ORDER BY cnt DESC
LIMIT 20;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 12. 검증 요약 리포트

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- 모든 검증 쿼리를 UNION으로 실행하는 대시보드
-- (실제 사용 시 위의 각 쿼리들을 CTE로 묶어 한 번에 실행)
-- 아래는 예시만:
WITH violations AS (
    SELECT 'FK_CSN_DPG001M' AS rule, COUNT(*) AS cnt
    FROM DPG001M d WHERE NOT EXISTS (SELECT 1 FROM CSC001M c WHERE c.CSN = d.CSN)
    UNION ALL
    SELECT 'DATE_LNB_EXEC_MAT', COUNT(*) FROM LNB001M WHERE NOT (EXEC_YMD < MAT_YMD)
    UNION ALL
    SELECT 'AMT_LNB_BAL_LIMIT', COUNT(*) FROM LNB001M WHERE NOT (LON_BAL <= LN_AMT)
    -- ... 전체 79개 규칙
)
SELECT rule, cnt,
       CASE WHEN cnt = 0 THEN 'PASS' ELSE 'FAIL' END AS status
FROM violations
ORDER BY cnt DESC;
